### ISSUE TITLE
Applet doesn't work properly with a multi-monitor setup.

### ISSUE THREAD

**Issue by Kartonrealista** [wiiznokes/clipboard-manager#41]
#### Bug Description
After adding it to the panel from the settings, it only appears on one of the panels in a multi-monitor setup. 
![image](https://github.com/wiiznokes/clipboard-manager/assets/63356574/9124f575-254f-48bb-af87-ca1c8251d333)

#### Expected Result
It should appear on all panels on all screens.
#### Steps to Reproduce
1. Use multiple screens with Panel setting "Show on display" set to "all".
2. Try to add applet to the panel.

**Comment by Kartonrealista** [comment]
The applet also crashes the panel if used in a multi-panel layout upon removal or just about any change to the panel (position, size, etc.)

**Comment by wiiznokes** [comment]
I know. The applet doesn't works with multiple instance. I did not think of this particular use case so I will look into it. This is due to the database being locked.

The panel freezing when an applet panic is a know issue
