### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by liberodark** [wiiznokes/clipboard-manager#48]
#### Bug Description

Hi,

Im just create this issue for help user if you have the same issue.

Best Regards

```
error: linking with `cc` failed: exit status: 1
= note: /usr/bin/ld: cannot find -lsqlite3: No such file or directory
          collect2: error: ld returned 1 exit status
```

#### Steps to Reproduce

```
git clone https://github.com/wiiznokes/clipboard-manager.git
cd clipboard-manager
just build-release
sudo just install
```

#### Possible Solutions

https://users.rust-lang.org/t/how-to-fix-error-linking-with-cc-failed-exit-status-1/108922
Probably : `sudo apt install -y sqlite3` but that not work for me... :(

**Comment by wiiznokes** [comment]
I recently switched to sqlite for the db. You will need to install `libsqlite3-dev` for building, and you need to have `sqlite3` at runtime.

For fedora, it will be `sqlite-devel` and `sqlite`, but there is an rpm package anyways.

You can keep this open so i remember to put a note in the readme :)
