### ISSUE TITLE
Does not work on cosmic alpha

### ISSUE THREAD

**Issue by qs5779** [wiiznokes/clipboard-manager#67]
#### Bug Description
$ /usr/bin/cosmic-ext-applet-clipboard-manager
2024-08-12T19:26:14.570739Z ERROR inside error: A required Wayland protocol (zwlr_data_control_manager_v1 version 1) is not supported by the compositor    
2024-08-12T19:26:14.576757Z ERROR A required Wayland protocol (zwlr_data_control_manager_v1 version 1) is not supported by the compositor

#### Expected Result
Expected to see an app icon and a clipboard manager

#### Steps to Reproduce
build and install per readme.md
run  /usr/bin/cosmic-ext-applet-clipboard-manager

#### Logs
Aug 12 15:26:14 dev cosmic-ext-applet-clipboard-manager[188903]: inside error: A required Wayland protocol (zwlr_data_control_manager_v1 version 1) is not supported by the compositor
Aug 12 15:26:14 dev cosmic-ext-applet-clipboard-manager[188903]: A required Wayland protocol (zwlr_data_control_manager_v1 version 1) is not supported by the compositor

**Comment by wiiznokes** [comment]
see https://github.com/wiiznokes/clipboard-manager/issues/61#issuecomment-2248605938

**Comment by qs5779** [comment]
After reading #61 I am now able to get it to run, but it doesn't seem to use the tray, but places a fixed icon in the upper right quadrant of my single monitor that doesn't seem movable. I was able to verify it did save a couple of clipboard entries, and also was able to clear them.  The "incognito" button didn't seem to do anything I could visually see.

**Comment by wiiznokes** [comment]
>  but it doesn't seem to use the tray, but places a fixed icon in the upper right quadrant of my single monitor that doesn't seem movable

what you mean ? This is just another cosmic applet, that get positioned via cosmic-panel.

Btw, the incognito is just a feature to deactivate the clipboard for some time

**Comment by qs5779** [comment]
To follow up, all seems working now. I have been a pop-os user for a number of years, but the new cosmic alpha will take some learning. I finally realized I needed to go into settings and add clipboard-manger to the applet section.

**Comment by wiiznokes** [comment]
Nice :)
