### ISSUE TITLE
Clipboard manger applet doesn't show any copied text

### ISSUE THREAD

**Issue by Department-stack** [wiiznokes/clipboard-manager#69]
Expected behavior: should show copied text in clipboard manager

Actual behavior: Clicking on the clipboard applet it shows no copied text

Logs: 
Aug 15 20:09:07 windows cosmic-ext-applet-clipboard-manager[2174]: Failed to initialize viewporter: the requested global was not found in the registry
Aug 15 20:09:15 windows cosmic-ext-applet-clipboard-manager[2174]: inside error: A required Wayland protocol (zwlr_data_control_manager_v1 version 1) is not supported by the compositor
Aug 15 20:09:15 windows cosmic-ext-applet-clipboard-manager[2174]: A required Wayland protocol (zwlr_data_control_manager_v1 version 1) is not supported by the compositor
~
~
~
~
~
~
~
~
(END)

Distribution: Fedora KDE 40

Desktop environment: COSMIC ALPHA

Kernel version: 6.9.11-200.fc40.x86_64

Processors: 2 × AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G

Memory: 3.5 GiB of RAM

Graphics: AMD Radeon R3 Graphics

Network adapter: Qualcomm Wireless-AC 802.11a/b/g/n/ac (2x2) Wi-Fi and Bluetooth 4.2 Combo, non-vPro

Laptop model: HP Chromebook 11A G8 EE

**Comment by Department-stack** [comment]
I have seen Workaround: write COSMIC_DATA_CONTROL_ENABLED=1 in /etc/environment however I dont have the folder "environment" in /ect/

**Comment by wiiznokes** [comment]
How did you install the applet ? You need to reboot so the variable take effect

**Comment by Department-stack** [comment]
I used the copr repo, and I did reboot

**Comment by qs5779** [comment]
> I have seen Workaround: write COSMIC_DATA_CONTROL_ENABLED=1 in /etc/environment however I dont have the folder "environment" in /ect/

If fedora doesn't have a /etc/environment file (not folder), then you should be able to get the same result by adding the variable to the /etc/profile file.

**Comment by Department-stack** [comment]
> > I have seen Workaround: write COSMIC_DATA_CONTROL_ENABLED=1 in /etc/environment however I dont have the folder "environment" in /ect/
> 
> If fedora doesn't have a /etc/environment file (not folder), then you should be able to get the same result by adding the variable to the /etc/profile file.

What file format do I use?

**Comment by Department-stack** [comment]
> What file format do I use?

Oh i see. I believe I misread what you said. Let me take the time later today to see if I can reslove this

**Comment by Department-stack** [comment]
I did the change and it now works. thanks a lot!
